In [71]:
import pandas as pd
from lazypredict.Supervised import LazyClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [55]:
df=pd.read_csv(r"C:\Users\PC\Downloads\Hotel Reservations.csv")

In [56]:
df

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,INN36271,3,0,2,6,Meal Plan 1,0,Room_Type 4,85,2018,8,3,Online,0,0,0,167.80,1,Not_Canceled
36271,INN36272,2,0,1,3,Meal Plan 1,0,Room_Type 1,228,2018,10,17,Online,0,0,0,90.95,2,Canceled
36272,INN36273,2,0,2,6,Meal Plan 1,0,Room_Type 1,148,2018,7,1,Online,0,0,0,98.39,2,Not_Canceled
36273,INN36274,2,0,0,3,Not Selected,0,Room_Type 1,63,2018,4,21,Online,0,0,0,94.50,0,Canceled
36274,INN36275,2,0,1,2,Meal Plan 1,0,Room_Type 1,207,2018,12,30,Offline,0,0,0,161.67,0,Not_Canceled

### Data Preprocessing

In [57]:
df=df.drop("Booking_ID",axis=1)

In [58]:
df.columns

Index(['no_of_adults', 'no_of_children', 'no_of_weekend_nights',
       'no_of_week_nights', 'type_of_meal_plan', 'required_car_parking_space',
       'room_type_reserved', 'lead_time', 'arrival_year', 'arrival_month',
       'arrival_date', 'market_segment_type', 'repeated_guest',
       'no_of_previous_cancellations', 'no_of_previous_bookings_not_canceled',
       'avg_price_per_room', 'no_of_special_requests', 'booking_status'],
      dtype='object')

In [59]:
df.type_of_meal_plan.unique()

array(['Meal Plan 1', 'Not Selected', 'Meal Plan 2', 'Meal Plan 3'],
      dtype=object)

In [62]:
df.room_type_reserved.unique()

array(['Room_Type 1', 'Room_Type 4', 'Room_Type 2', 'Room_Type 6',
       'Room_Type 5', 'Room_Type 7', 'Room_Type 3'], dtype=object)

In [63]:
df.type_of_meal_plan.value_counts()

Meal Plan 1     27835
Not Selected     5130
Meal Plan 2      3305
Meal Plan 3         5
Name: type_of_meal_plan, dtype: int64

In [67]:
most_frequent_value=df['type_of_meal_plan'].mode()[0]
df['type_of_meal_plan'] = df['type_of_meal_plan'].replace('Not Selected', most_frequent_value)
df

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled
1,2,0,2,3,Meal Plan 1,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled
2,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled
3,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled
4,2,0,1,1,Meal Plan 1,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,3,0,2,6,Meal Plan 1,0,Room_Type 4,85,2018,8,3,Online,0,0,0,167.80,1,Not_Canceled
36271,2,0,1,3,Meal Plan 1,0,Room_Type 1,228,2018,10,17,Online,0,0,0,90.95,2,Canceled
36272,2,0,2,6,Meal Plan 1,0,Room_Type 1,148,2018,7,1,Online,0,0,0,98.39,2,Not_Canceled
36273,2,0,0,3,Meal Plan 1,0,Room_Type 1,63,2018,4,21,Online,0,0,0,94.50,0,Canceled
36274,2,0,1,2,Meal Plan 1,0,Room_Type 1,207,2018,12,30,Offline,0,0,0,161.67,0,Not_Canceled

In [68]:
df.type_of_meal_plan.unique()

array(['Meal Plan 1', 'Meal Plan 2', 'Meal Plan 3'], dtype=object)

In [69]:
# Encoding
categorical_columns = ["type_of_meal_plan", "room_type_reserved", "market_segment_type", "booking_status"]
encoder = LabelEncoder()
le=LabelEncoder()
for i in categorical_columns:
    df[i]=le.fit_transform(df[i])

In [70]:
df

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,2,0,1,2,0,0,0,224,2017,10,2,3,0,0,0,65.00,0,1
1,2,0,2,3,0,0,0,5,2018,11,6,4,0,0,0,106.68,1,1
2,1,0,2,1,0,0,0,1,2018,2,28,4,0,0,0,60.00,0,0
3,2,0,0,2,0,0,0,211,2018,5,20,4,0,0,0,100.00,0,0
4,2,0,1,1,0,0,0,48,2018,4,11,4,0,0,0,94.50,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,3,0,2,6,0,0,3,85,2018,8,3,4,0,0,0,167.80,1,1
36271,2,0,1,3,0,0,0,228,2018,10,17,4,0,0,0,90.95,2,0
36272,2,0,2,6,0,0,0,148,2018,7,1,4,0,0,0,98.39,2,1
36273,2,0,0,3,0,0,0,63,2018,4,21,4,0,0,0,94.50,0,0
36274,2,0,1,2,0,0,0,207,2018,12,30,3,0,0,0,161.67,0,1

In [72]:
X = df.drop("booking_status", axis=1)
y = df["booking_status"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


clf = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=None)
models, predictions = clf.fit(X_train, X_test, y_train, y_test)

print(models)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 29/29 [02:57<00:00,  6.11s/it]

[LightGBM] [Info] Number of positive: 19551, number of negative: 9469
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001340 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 667
[LightGBM] [Info] Number of data points in the train set: 29020, number of used features: 17
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.673708 -> initscore=0.725003
[LightGBM] [Info] Start training from score 0.725003
                               Accuracy  Balanced Accuracy  ROC AUC  F1 Score  \
Model
RandomForestClassifier             0.90               0.88     0.88      0.90
BaggingClassifier                  0.89               0.88     0.88      0.89
ExtraTreesClassifier               0.90               0.88     0.88      0.90
XGBClassifier                      0.89               0.87     0.87      0.89
LGBMClassifier                     0.88               0.86     0.86      0.88
DecisionTreeClassifier             0.87               0.86     0.86      0.87
LabelPropagation                   0.85               0.83     0.83      0.85
LabelSpreading                     0.85               0.83     0.83      0.85
ExtraTreeClassifier                0.85               0.83     0.83      0.85
KNeighborsClassifier               0.85               0.82     0.82      0.85
SVC                                0.84               0.80     0.80      0.84
AdaBoostClassifier                 0.82               0.78     0.78      0.81
NearestCentroid                    0.76               0.76     0.76      0.77
LogisticRegression                 0.81               0.76     0.76      0.80
NuSVC                              0.81               0.75     0.75      0.81
CalibratedClassifierCV             0.80               0.75     0.75      0.80
LinearSVC                          0.80               0.75     0.75      0.80
SGDClassifier                      0.80               0.75     0.75      0.79
LinearDiscriminantAnalysis         0.79               0.74     0.74      0.79
RidgeClassifier                    0.80               0.74     0.74      0.79
RidgeClassifierCV                  0.80               0.74     0.74      0.79
BernoulliNB                        0.76               0.71     0.71      0.76
Perceptron                         0.72               0.66     0.66      0.71
QuadraticDiscriminantAnalysis      0.48               0.60     0.60      0.43
PassiveAggressiveClassifier        0.68               0.58     0.58      0.65
GaussianNB                         0.45               0.58     0.58      0.39
DummyClassifier                    0.67               0.50     0.50      0.53

                               Time Taken
Model
RandomForestClassifier               2.99
BaggingClassifier                    0.81
ExtraTreesClassifier                 2.27
XGBClassifier                        0.32
LGBMClassifier                       0.21
DecisionTreeClassifier               0.12
LabelPropagation                    55.36
LabelSpreading                      78.29
ExtraTreeClassifier                  0.04
KNeighborsClassifier                 0.58
SVC                                 13.12
AdaBoostClassifier                   0.69
NearestCentroid                      0.04
LogisticRegression                   0.08
NuSVC                               19.68
CalibratedClassifierCV               0.25
LinearSVC                            1.66
SGDClassifier                        0.07
LinearDiscriminantAnalysis           0.12
RidgeClassifier                      0.04
RidgeClassifierCV                    0.05
BernoulliNB                          0.04
Perceptron                           0.04
QuadraticDiscriminantAnalysis        0.09
PassiveAggressiveClassifier          0.05
GaussianNB                           0.03
DummyClassifier                      0.02

### RandomForestClassifier is the best model

In [73]:
predictions

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
RandomForestClassifier,0.90,0.88,0.88,0.90,2.99
BaggingClassifier,0.89,0.88,0.88,0.89,0.81
ExtraTreesClassifier,0.90,0.88,0.88,0.90,2.27
XGBClassifier,0.89,0.87,0.87,0.89,0.32
LGBMClassifier,0.88,0.86,0.86,0.88,0.21
DecisionTreeClassifier,0.87,0.86,0.86,0.87,0.12
LabelPropagation,0.85,0.83,0.83,0.85,55.36
LabelSpreading,0.85,0.83,0.83,0.85,78.29
ExtraTreeClassifier,0.85,0.83,0.83,0.85,0.04
KNeighborsClassifier,0.85,0.82,0.82,0.85,0.58
SVC,0.84,0.80,0.80,0.84,13.12
AdaBoostClassifier,0.82,0.78,0.78,0.81,0.69
NearestCentroid,0.76,0.76,0.76,0.77,0.04
LogisticRegression,0.81,0.76,0.76,0.80,0.08
NuSVC,0.81,0.75,0.75,0.81,19.68
CalibratedClassifierCV,0.80,0.75,0.75,0.80,0.25
LinearSVC,0.80,0.75,0.75,0.80,1.66
SGDClassifier,0.80,0.75,0.75,0.79,0.07
LinearDiscriminantAnalysis,0.79,0.74,0.74,0.79,0.12
RidgeClassifier,0.80,0.74,0.74,0.79,0.04
RidgeClassifierCV,0.80,0.74,0.74,0.79,0.05
BernoulliNB,0.76,0.71,0.71,0.76,0.04
Perceptron,0.72,0.66,0.66,0.71,0.04
QuadraticDiscriminantAnalysis,0.48,0.60,0.60,0.43,0.09
PassiveAggressiveClassifier,0.68,0.58,0.58,0.65,0.05
GaussianNB,0.45,0.58,0.58,0.39,0.03
DummyClassifier,0.67,0.50,0.50,0.53,0.02

### Model after Lazypredict

In [75]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)


y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9046175051688491